export const FIND_PRODUCT_REQUEST = 'FIND_PRODUCT_REQUEST';
export const FIND_PRODUCT_SUCCESS = 'FIND_PRODUCT_SUCCESS';
export const FIND_PRODUCT_FAIL = 'FIND_PRODUCT_FAIL';
export const ORDER_BY_FILT = 'ORDER_BY_FILT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const MODIFIED_PRODUCT = 'MODIFIED_PRODUCT';