export const FIND_PRODUCT_SUCCESS = 'FIND_PRODUCT_SUCCESS';
export const ORDER_BY_FILT = 'ORDER_BY_FILT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_DETAILS = 'GET_DETAILS';
